<?php

/**
 * @file
 * Contains escrutinio.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\HtmlCommand;

use Drupal\reportes\Controller\FuncionesController;
use Drupal\node\Entity\Node;
use Drupal\Core\Form\FormStateInterface;
use \Drupal\Core\Session\AccountInterface;
/**
 * Implements hook_theme().
 */
function alertas_theme($existing, $type, $theme, $path) {
    $variables = array(
        'theme_alertas' => array(
            'variables' => array(
                'contenido' => null,
                //'biblioteca' => null,
            ),
            'template' => 'alertas',
        ),
    );
    return $variables;
}

function alertas_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    
	if ($form_id == 'node_actividades_misionales_edit_form' || $form_id == 'node_actividades_misionales_form' || $form_id == 'node_actividad_ejecutada_form' || $form_id == 'node_actividad_ejecutada_edit_form') {
    	$form['#attached']['library'][] = 'alertas/alertas';
    	return $form;
  	}
}

?>

