services:
  configuraciones.access:
    class: \Drupal\configuraciones\EventSubscriber\RequestUrl
    arguments: ['@current_user', '@current_route_match', '@entity_type.manager']
    tags:
      - {name: event_subscriber}
